all:
  hosts:
    nuc1:
      ansible_host: 192.168.1.10
      ansible_user: user1
      ansible_ssh_pass: password1
    nuc2:
      ansible_host: 192.168.1.11
      ansible_user: user2
      ansible_ssh_pass: password2
    nuc3:
      ansible_host: 192.168.1.12
      ansible_user: user3
      ansible_ssh_pass: password3
    nuc4:
      ansible_host: 192.168.1.13
      ansible_user: user4
      ansible_ssh_pass: password4
  children:
    nucs:
      hosts:
        nuc1:
        nuc2:
        nuc3:
        nuc4:
