---
- name: Copy script to NUK2
  copy:
    src: script_nuk2.sh
    dest: /home/user2/script_nuk2.sh
    mode: '0755'

- name: Execute script on NUK2
  command: /home/user2/script_nuk2.sh

- name: Reboot NUK2
  reboot:
    msg: "Reboot initiated by Ansible"
    pre_reboot_delay: 10
    post_reboot_delay: 60
    test_command: whoami
